export default {
  SET_SEARCH_WORD: 'SET_SEARCH_WORD',

  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SET_SIGNATURE: 'SET_SIGNATURE',

  SET_SIGNATURE: 'SET_SIGNATURE',

  OPEN_BUY_COLLECTIBLE_DIALOG: 'OPEN_BUY_COLLECTIBLE_DIALOG',
  CLOSE_BUY_COLLECTIBLE_DIALOG: 'CLOSE_BUY_COLLECTIBLE_DIALOG',

  SET_BUY_COLLECTIBLE_DATA: 'SET_BUY_COLLECTIBLE_DATA'

};
